name: Submit Paclet

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

env:
  RESOURCE_PUBLISHER_TOKEN: ${{ secrets.RESOURCE_PUBLISHER_TOKEN }}
  WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAMSCRIPT_ENTITLEMENTID }}
  WLPR_PACLET_SITE: https://resources.wolframcloud.com/PacletRepository/pacletsite

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    container:
      image: wolframresearch/wolframengine:latest
      options: --user root
    env:
      WOLFRAM_SYSTEM_ID: Linux-x86-64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check
        uses: WolframResearch/check-paclet@v1.11.0
        with:
          target: Submit
          paclet_cicd_version: 0.36.0

    # - name: UploadWorkflowValues
    #   if: always() && env.PACLET_WORKFLOW_VALUES
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: paclet-workflow-values
    #     path: ${{ env.PACLET_WORKFLOW_VALUES }}
    #     if-no-files-found: ignore

  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: wolframresearch/wolframengine:latest
      options: --user root
    env:
      WOLFRAM_SYSTEM_ID: Linux-x86-64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Test
        uses: WolframResearch/test-paclet@v1.11.0
        with:
          target: Submit
          paclet_cicd_version: 0.36.0

    # - name: UploadWorkflowValues
    #   if: always() && env.PACLET_WORKFLOW_VALUES
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: paclet-workflow-values
    #     path: ${{ env.PACLET_WORKFLOW_VALUES }}
    #     if-no-files-found: ignore

  submit:
    name: Submit
    needs: [check, test]
    runs-on: ubuntu-latest
    container:
      image: wolframresearch/wolframengine:latest
      options: --user root
    env:
      WOLFRAM_SYSTEM_ID: Linux-x86-64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Submit
        uses: WolframResearch/submit-paclet@v1.11.0
        with:
          paclet_cicd_version: 0.36.0

      - name: UploadArtifact
        uses: actions/upload-artifact@v4
        with:
          path: ${{ env.PACLET_BUILD_DIR }}
          if-no-files-found: ignore

      - name: UploadWorkflowValues
        if: always() && env.PACLET_WORKFLOW_VALUES
        uses: actions/upload-artifact@v4
        with:
          name: paclet-workflow-values
          path: ${{ env.PACLET_WORKFLOW_VALUES }}
          if-no-files-found: ignore
